### PR TITLE
Added space before if, while, for, try, catch, switch parentheses.

### PR DESCRIPTION
**Pull request by dkim89**
Modified settings.jar _/codestyles/Default_1_.xml_ file for the following options to include space between conditional keyword and parentheses:

```xml
<codeStyleSettings language="JAVA">
    <option name="SPACE_BEFORE_IF_PARENTHESES" value="true" />
    <option name="SPACE_BEFORE_WHILE_PARENTHESES" value="true" />
    <option name="SPACE_BEFORE_FOR_PARENTHESES" value="true" />
    <option name="SPACE_BEFORE_TRY_PARENTHESES" value="true" />
    <option name="SPACE_BEFORE_CATCH_PARENTHESES" value="true" />
    <option name="SPACE_BEFORE_SWITCH_PARENTHESES" value="true" />
```

### CODE REVIEW

**Comment by sigmabeta** [comment]
YES. This has been driving me nuts for weeks. 

@dkim89 is representing the green team at RZ West bigtime

**Comment by kenkyee** [comment]
there was a long discussion about snuggled stuff or not a while back..I think Android was trying to match iOS and Python standards or something.
I hate it but I didn't define the standard...

**Comment by markpragma** [comment]
So this would be the space, e.g. in `if (`, yes?

**Comment by kenkyee** [comment]
Yes, this would unsnuggled the open paren

**Comment by markpragma** [comment]
Cool. Merging.

**Comment by octohub** [comment]
@dkim89 Android Studio fails to import this updated `settings.jar` file. Someone else should attempt importing to verify it a issue that isn't just on my machine.

**Pull request merged**
