### PR TITLE
Label code style with the current date

### PR DESCRIPTION
**Pull request by sigmabeta**
A few quick fixes:

-The code style jar contained things other than a code style. Those things were removed. If they were included intentionally, please let me know and I'll undo this.
-The code style was labeled "Default". It is now labeled "Raizlabs <today's date>". All amendments to the code style jar should do this too, so it's easy to tell what version you're using.
-The jar was labeled "settings.jar". It isn't anymore.

### CODE REVIEW

**Comment by kenkyee** [comment]
are there any missing files?  Looks like the only file change is settings.jar?

**Comment by sigmabeta** [comment]
Good eye.

**Comment by markpragma** [comment]
Please list out the things that were removed.

**Comment by sigmabeta** [comment]
@markpragma here's what I didn't include in this JAR:

screen shot 2016-05-02 at 2 11 00 pm

That's a screen-cap taken from attempting to import the previous `settings.jar`. I don't know what any of that stuff is or why it belongs in this file.

**Comment by sigmabeta** [comment]
Also, I can't actually get it to list those things in a more readable format.

**Comment by markpragma** [comment]
Does the markdown require any updates based on these changes?

**Comment by sigmabeta** [comment]
There are links to the `settings.jar` file. I can change those links.

**Pull request merged**
